// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"dislinkt/job_offer_service/ent/joboffer"
	"dislinkt/job_offer_service/ent/skill"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// JobOfferCreate is the builder for creating a JobOffer entity.
type JobOfferCreate struct {
	config
	mutation *JobOfferMutation
	hooks    []Hook
}

// SetProfileID sets the "profile_id" field.
func (joc *JobOfferCreate) SetProfileID(s string) *JobOfferCreate {
	joc.mutation.SetProfileID(s)
	return joc
}

// SetCompany sets the "company" field.
func (joc *JobOfferCreate) SetCompany(s string) *JobOfferCreate {
	joc.mutation.SetCompany(s)
	return joc
}

// SetPosition sets the "position" field.
func (joc *JobOfferCreate) SetPosition(s string) *JobOfferCreate {
	joc.mutation.SetPosition(s)
	return joc
}

// SetDescription sets the "description" field.
func (joc *JobOfferCreate) SetDescription(s string) *JobOfferCreate {
	joc.mutation.SetDescription(s)
	return joc
}

// SetCriteria sets the "criteria" field.
func (joc *JobOfferCreate) SetCriteria(s string) *JobOfferCreate {
	joc.mutation.SetCriteria(s)
	return joc
}

// SetCreatedAt sets the "created_at" field.
func (joc *JobOfferCreate) SetCreatedAt(t time.Time) *JobOfferCreate {
	joc.mutation.SetCreatedAt(t)
	return joc
}

// AddRequireIDs adds the "requires" edge to the Skill entity by IDs.
func (joc *JobOfferCreate) AddRequireIDs(ids ...int) *JobOfferCreate {
	joc.mutation.AddRequireIDs(ids...)
	return joc
}

// AddRequires adds the "requires" edges to the Skill entity.
func (joc *JobOfferCreate) AddRequires(s ...*Skill) *JobOfferCreate {
	ids := make([]int, len(s))
	for i := range s {
		ids[i] = s[i].ID
	}
	return joc.AddRequireIDs(ids...)
}

// Mutation returns the JobOfferMutation object of the builder.
func (joc *JobOfferCreate) Mutation() *JobOfferMutation {
	return joc.mutation
}

// Save creates the JobOffer in the database.
func (joc *JobOfferCreate) Save(ctx context.Context) (*JobOffer, error) {
	var (
		err  error
		node *JobOffer
	)
	if len(joc.hooks) == 0 {
		if err = joc.check(); err != nil {
			return nil, err
		}
		node, err = joc.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*JobOfferMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = joc.check(); err != nil {
				return nil, err
			}
			joc.mutation = mutation
			if node, err = joc.sqlSave(ctx); err != nil {
				return nil, err
			}
			mutation.id = &node.ID
			mutation.done = true
			return node, err
		})
		for i := len(joc.hooks) - 1; i >= 0; i-- {
			if joc.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = joc.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, joc.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (joc *JobOfferCreate) SaveX(ctx context.Context) *JobOffer {
	v, err := joc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (joc *JobOfferCreate) Exec(ctx context.Context) error {
	_, err := joc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (joc *JobOfferCreate) ExecX(ctx context.Context) {
	if err := joc.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (joc *JobOfferCreate) check() error {
	if _, ok := joc.mutation.ProfileID(); !ok {
		return &ValidationError{Name: "profile_id", err: errors.New(`ent: missing required field "JobOffer.profile_id"`)}
	}
	if _, ok := joc.mutation.Company(); !ok {
		return &ValidationError{Name: "company", err: errors.New(`ent: missing required field "JobOffer.company"`)}
	}
	if _, ok := joc.mutation.Position(); !ok {
		return &ValidationError{Name: "position", err: errors.New(`ent: missing required field "JobOffer.position"`)}
	}
	if _, ok := joc.mutation.Description(); !ok {
		return &ValidationError{Name: "description", err: errors.New(`ent: missing required field "JobOffer.description"`)}
	}
	if _, ok := joc.mutation.Criteria(); !ok {
		return &ValidationError{Name: "criteria", err: errors.New(`ent: missing required field "JobOffer.criteria"`)}
	}
	if _, ok := joc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "JobOffer.created_at"`)}
	}
	return nil
}

func (joc *JobOfferCreate) sqlSave(ctx context.Context) (*JobOffer, error) {
	_node, _spec := joc.createSpec()
	if err := sqlgraph.CreateNode(ctx, joc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{err.Error(), err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	return _node, nil
}

func (joc *JobOfferCreate) createSpec() (*JobOffer, *sqlgraph.CreateSpec) {
	var (
		_node = &JobOffer{config: joc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: joboffer.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: joboffer.FieldID,
			},
		}
	)
	if value, ok := joc.mutation.ProfileID(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: joboffer.FieldProfileID,
		})
		_node.ProfileID = value
	}
	if value, ok := joc.mutation.Company(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: joboffer.FieldCompany,
		})
		_node.Company = value
	}
	if value, ok := joc.mutation.Position(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: joboffer.FieldPosition,
		})
		_node.Position = value
	}
	if value, ok := joc.mutation.Description(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: joboffer.FieldDescription,
		})
		_node.Description = value
	}
	if value, ok := joc.mutation.Criteria(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: joboffer.FieldCriteria,
		})
		_node.Criteria = value
	}
	if value, ok := joc.mutation.CreatedAt(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: joboffer.FieldCreatedAt,
		})
		_node.CreatedAt = value
	}
	if nodes := joc.mutation.RequiresIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   joboffer.RequiresTable,
			Columns: joboffer.RequiresPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: skill.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// JobOfferCreateBulk is the builder for creating many JobOffer entities in bulk.
type JobOfferCreateBulk struct {
	config
	builders []*JobOfferCreate
}

// Save creates the JobOffer entities in the database.
func (jocb *JobOfferCreateBulk) Save(ctx context.Context) ([]*JobOffer, error) {
	specs := make([]*sqlgraph.CreateSpec, len(jocb.builders))
	nodes := make([]*JobOffer, len(jocb.builders))
	mutators := make([]Mutator, len(jocb.builders))
	for i := range jocb.builders {
		func(i int, root context.Context) {
			builder := jocb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*JobOfferMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				nodes[i], specs[i] = builder.createSpec()
				var err error
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, jocb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, jocb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{err.Error(), err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, jocb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (jocb *JobOfferCreateBulk) SaveX(ctx context.Context) []*JobOffer {
	v, err := jocb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (jocb *JobOfferCreateBulk) Exec(ctx context.Context) error {
	_, err := jocb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (jocb *JobOfferCreateBulk) ExecX(ctx context.Context) {
	if err := jocb.Exec(ctx); err != nil {
		panic(err)
	}
}
