// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"dislinkt/job_offer_service/ent/joboffer"
	"dislinkt/job_offer_service/ent/predicate"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// JobOfferDelete is the builder for deleting a JobOffer entity.
type JobOfferDelete struct {
	config
	hooks    []Hook
	mutation *JobOfferMutation
}

// Where appends a list predicates to the JobOfferDelete builder.
func (jod *JobOfferDelete) Where(ps ...predicate.JobOffer) *JobOfferDelete {
	jod.mutation.Where(ps...)
	return jod
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (jod *JobOfferDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(jod.hooks) == 0 {
		affected, err = jod.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*JobOfferMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			jod.mutation = mutation
			affected, err = jod.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(jod.hooks) - 1; i >= 0; i-- {
			if jod.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = jod.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, jod.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (jod *JobOfferDelete) ExecX(ctx context.Context) int {
	n, err := jod.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (jod *JobOfferDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: joboffer.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: joboffer.FieldID,
			},
		},
	}
	if ps := jod.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return sqlgraph.DeleteNodes(ctx, jod.driver, _spec)
}

// JobOfferDeleteOne is the builder for deleting a single JobOffer entity.
type JobOfferDeleteOne struct {
	jod *JobOfferDelete
}

// Exec executes the deletion query.
func (jodo *JobOfferDeleteOne) Exec(ctx context.Context) error {
	n, err := jodo.jod.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{joboffer.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (jodo *JobOfferDeleteOne) ExecX(ctx context.Context) {
	jodo.jod.ExecX(ctx)
}
